# Generated by Django 3.1.7 on 2021-07-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=200)),
                ('points', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'areas1',
            },
        ),
        migrations.CreateModel(
            name='Area2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=200)),
                ('points', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('color1', models.CharField(max_length=200)),
                ('color2', models.CharField(max_length=200)),
                ('angle', models.IntegerField()),
            ],
            options={
                'db_table': 'areas2',
            },
        ),
    ]
